### PR TITLE
Changes to random date generation methods

### PR DESCRIPTION
**Pull request by felipeferri**
I was using SwiftRandom for generating random dates between time intervals defined by the user.

I found out that if the user selected a number of days less than 1 the method Random.randomWithinDaysBeforeToday() could generate dates in the future (because a positive random number of hours, minutes and seconds are added to a negative number of days in order to generate the new date).

So I created a new method, Date.random(between: Date, and: Date), which allows selecting arbitrary initial and final dates for generating random dates; then I used it as a base for reimplementing randomWithinDaysBeforeToday(). Its implementation is simpler than the one that came before.

I also added some test cases that make sure random dates are not generated in the future and stay in the defined interval.

### CODE REVIEW

**Comment by azakordonets** [comment]
@felipeferri just an FYI - there are no changes in your merge request..

**Comment by felipeferri** [comment]
Hmmmm I don't know what I'm doing wrong, if I click on the Files Changed tab I can see the changes. :-/

**Comment by azakordonets** [comment]
@felipeferri yeah, i can see it now. Before it was empty. Maybe some Github glitch

**Comment by thellimist** [comment]
README file is not updated for `random(between initial: Date, and final:Date) -> Date`. Please add documentation. Thanks

**Comment by felipeferri** [comment]
Done!

**Pull request merged**
