### PR TITLE
Master

### PR DESCRIPTION
**Pull request by krider2010**
Added the ability to download gravatar images at various sizes (can be used for profiles, backgrounds, etc.)

### CODE REVIEW

**Comment by thellimist** [comment]
It'd be great if instead of assigning the image in main_thread the function would just call the completion block in main_thread. Just for visualisation

Instead of
```
        Randoms.randomGravatar(completion: { (image, error) -> Void in
            dispatch_async(dispatch_get_main_queue()) {
                self.gravatar.image = image
            }
        })
```

This would be better
```
        Randoms.randomGravatar(completion: { (image, error) -> Void in
            self.gravatar.image = image
        })
```

**Comment by thellimist** [comment]
Also along with of giving GravatarStyle as an argument I think it'd be more simple if it just selected a random GravatarStyle. What do you think about this since its your use case?

**Comment by krider2010** [comment]
Agree on the thread thing! Very good point.

It would be simpler with a random gravatar style, but I'm anal over wanting consistency of the style in my app during development even. Especially if clients see demo data :) I think I'd rather add a new method for that then there are both.

**Comment by thellimist** [comment]
@krider2010 Since you used the same name in both funtions and they both have all parameters optional which make the function ambiguous. Change the name of `randomGravatar(style: Randoms.GravatarStyle = .Standard, size: Int = 80, completion: ((image: UIImage?, error: NSError?) -> Void)?)` to something more noticable. Btw this function is not random so it would also be confusing to call it `randomGravatar`. Maybe `createGravatar`?


---
PS: just for better practice :)

```
    public static func randomGravatar(size: Int = 80, completion: ((image: UIImage?, error: NSError?) -> Void)?) {
        let options = Randoms.GravatarStyle.allValues
        Randoms.randomGravatar(options.randomItem(), size: size, completion: completion)
    }
```

**Comment by goktugyil** [comment]
Nice feature :+1:

**Comment by krider2010** [comment]
Array.randomItem() - completely missed last night. I was getting tired obviously! I've renamed the initial one creation, the second random since it is a random image comparatively.

**Pull request merged**
